apiVersion: v1
kind: Pod
spec:
  containers:
  - name: dind
    image: docker:19.03.12-dind
    command:
    - cat
    securityContext: 
      privileged: true 
    tty: true
  imagePullSecrets:
  - name: ociregistry