apiVersion: v1
kind: Pod
spec:
  containers:
  - name: helm
    image: us-phoenix-1.ocir.io/axxalonri6o1/devops/alpine-terraform:1.0.3
    command:
    - cat
    tty: true
  imagePullSecrets:
  - name: ociregistry